demo_site/pages/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from demo_site.pages import views

urlpatterns = [
    # Test stuff
    url(r'^grid/(?P<slug>[-\w\d]+)$', views.PageGridList.as_view(), name='grid-list'),
    url(r'^grid/(?P<slug>[-\w\d]+)/new$', views.PageGridCreate.as_view(), name='grid-new'),


    url(r'^grid/edit/(?P<pk>\d+)$', views.PageGridUpdate.as_view(), name='grid-edit'),
    url(r'^grid/delete/(?P<pk>\d+)$', views.PageGridDelete.as_view(), name='grid-delete'),


    url(r'^grid/edit/preview/(?P<pk>\d+)$', views.PageGridUpdate2.as_view(), name='grid-edit2'),
    url(r'^grid/delete/preview/(?P<pk>\d+)$', views.PageGridDelete2.as_view(), name='grid-delete2'),

    # Real stuff
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^page$', views.PageList.as_view(), name='page-list'),
    url(r'^page/new/', views.PageListCreate.as_view(), name='page-new'),
    url(r'^page/edit/(?P<pk>\d+)$', views.PageUpdate.as_view(), name='page-edit'),
    url(r'^page/delete/(?P<pk>\d+)$', views.PageDelete.as_view(),name='page-delete'),
    url(r'^article$', views.PageArticleList.as_view(), name='article-list'),
    url(r'^article/(?P<pk>\d+)$', views.PageArticleDetail.as_view(), name='article-detail'),
    url(r'^article/new$', views.PageArticleCreate.as_view(), name='article-new'),
    url(r'^article/edit/(?P<pk>\d+)$', views.PageArticleUpdate.as_view(), name='article-edit'),
    url(r'^article/delete/(?P<pk>\d+)$', views.PageArticleDelete.as_view(), name='article-delete'),
    url(r'^faq$', views.PageFAQList.as_view(), name='faq-list'),
    url(r'^faq/(?P<pk>\d+)$', views.PageFAQDetail.as_view(), name='faq-detail'),
    url(r'^faq/new$', views.PageFAQCreate.as_view(), name='faq-new'),
    url(r'^faq/edit/(?P<pk>\d+)$', views.PageFAQUpdate.as_view(), name='faq-edit'),
    url(r'^faq/delete/(?P<pk>\d+)$', views.PageFAQDelete.as_view(), name='faq-delete'),
    url(r'^link$', views.PageLinkList.as_view(), name='link-list'),
    url(r'^link/(?P<pk>\d+)$', views.PageLinkDetail.as_view(), name='link-detail'),
    url(r'^link/new$', views.PageLinkCreate.as_view(), name='link-new'),
    url(r'^link/edit/(?P<pk>\d+)$', views.PageLinkUpdate.as_view(), name='link-edit'),
    url(r'^link/delete/(?P<pk>\d+)$', views.PageLinkDelete.as_view(), name='link-delete'),
    url(r'^youtubelink$', views.PageYoutubeLinkList.as_view(), name='youtubelink-list'),
    url(r'^youtubelink/(?P<pk>\d+)$', views.PageYoutubeLinkDetail.as_view(), name='youtubelink-detail'),
    url(r'^youtubelink/new$', views.PageYoutubeLinkCreate.as_view(), name='youtubelink-new'),
    url(r'^youtubelink/edit/(?P<pk>\d+)$', views.PageYoutubeLinkUpdate.as_view(), name='youtubelink-edit'),
    url(r'^youtubelink/delete/(?P<pk>\d+)$', views.PageYoutubeLinkDelete.as_view(),
        name='youtubelink-delete'),
    url(r'^facebooklink$', views.PageFacebookLinkList.as_view(), name='facebooklink-list'),
    url(r'^facebooklink/(?P<pk>\d+)$', views.PageFacebookLinkDetail.as_view(), name='facebooklink-detail'),
    url(r'^facebooklink/new$', views.PageFacebookLinkCreate.as_view(), name='facebooklink-new'),
    url(r'^facebooklink/edit/(?P<pk>\d+)$', views.PageFacebookLinkUpdate.as_view(), name='facebooklink-edit'),
    url(r'^facebooklink/delete/(?P<pk>\d+)$', views.PageFacebookLinkDelete.as_view(),
        name='facebooklink-delete'),
    # url(r'^(?P<slug>[-\w\d]+)$', views.PageView, name='page'),
    #url(r'^', views.IndexView, name='default'),
]

demo_site/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import RedirectView
from .pages import views

urlpatterns = patterns(
    '',
    url(r'', include('django.contrib.auth.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^pages/', include('demo_site.pages.urls', namespace='pages')),

    url(r'^(?P<slug>[-\w\d]+)$', views.PageDetail.as_view(), name='page-detail'),
    url(r'^.*$', RedirectView.as_view(url='pages/page', permanent=False), name='index'),
)

demo_site/pages/templates/semantic-ui/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <!-- Standard Meta -->
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="A web application to automate network tasks.">
    <meta name="author" content="Formatics">
    <link rel="icon" href="/static/favicon.ico">
    <title>Django Pages - {% block title %}{% endblock %}</title>
    <!--- Stylesheets --->
    <link rel="stylesheet" type="text/css" href="{% static "semantic-ui/semantic.min.css" %}">
    {% block css_header %}{% endblock %}
    <!--- JavaScript --->
    <script src="{% static "semantic-ui/jquery/jquery-2.1.3.min.js" %}"></script>
    <script src="{% static "semantic-ui/semantic.min.js" %}"></script>
    {% block javascript_header %}{% endblock %}

</head>
<body>
{#    <div class="ui inline cookie nag">#}
{#      <span class="title">#}
{#        We use cookies to ensure you get the best experience on our website#}
{#      </span>#}
{#      <i class="close icon"></i>#}
{#    </div>#}
{##}
{#    <script>#}
{#        $('.cookie.nag')#}
{#          .nag({#}
{#            key      : 'accepts-cookies',#}
{#            value    : true#}
{#          })#}
{#        ;#}
{#    </script>#}

    {% block menu_header %}
        {% include "semantic-ui/menu_header.html" %}
    {% endblock %}

    {% block statusbar %}
        {% include "semantic-ui/statusbar.html" %}
    {% endblock %}

    <div class="ui segment">
    {% block content %}
    {% endblock %}
    </div>


    <!-- SIDE BAR -->



    {% block footer %}
        {% include "semantic-ui/footer.html" %}
    {% endblock %}
{% block javascript_footer %}{% endblock %}
<script>
    $('#version_popup').popup({position : 'bottom right'});
    $('.dropdown')
      .dropdown({
        transition: 'drop'
      })
    ;
</script>
</body>
</html>

demo_site/pages/templates/semantic-ui/menu_header.html
<div class="ui inverted menu">


    <a class="item"><i class="home icon"></i>

    </a>

    <a class="item active">
        Overview
    </a>

    <div class="ui dropdown item">
        Pages <i class="dropdown icon"></i>

        <div class="menu">
            <a href="{% url "pages:page-list" %}" class="item"> <i class="align justify icon"></i>View Pages</a>
            <a href="{% url "pages:page-new" %}" class="item"> <i class="add icon"></i>Create Pages</a>
        </div>
    </div>


    <div class="ui dropdown item">
        Articles <i class="dropdown icon"></i>

        <div class="menu">
            <a href="{% url "pages:article-list" %}" class="item"> <i class="align justify icon"></i>View Articles</a>
            <a href="{% url "pages:article-new" %}" class="item"> <i class="add icon"></i>Create Article</a>
        </div>
    </div>


    <div class="ui dropdown item">
        FAQ <i class="dropdown icon"></i>

        <div class="menu">
            <a href="{% url "pages:faq-list" %}" class="item"> <i class="align justify icon"></i>View FAQ</a>
            <a href="{% url "pages:faq-new" %}" class="item"> <i class="add icon"></i>Create FAQ</a>
        </div>
    </div>

    <div class="ui dropdown item">
        Links <i class="dropdown icon"></i>

        <div class="menu">
            <a href="{% url "pages:link-list" %}" class="item"> <i class="align justify icon"></i>View Links</a>
            <a href="{% url "pages:link-new" %}" class="item"> <i class="add icon"></i>Create Link</a>
        </div>
    </div>

    <div class="ui dropdown item">
        Facebook Links <i class="dropdown icon"></i>

        <div class="menu">
            <a href="{% url "pages:facebooklink-list" %}" class="item"> <i class="align justify icon"></i>View Facebook
                Links</a>
            <a href="{% url "pages:facebooklink-new" %}" class="item"> <i class="add icon"></i>Create Facebook Link</a>
        </div>
    </div>

    <div class="ui dropdown item">
        Youtube Links <i class="dropdown icon"></i>

        <div class="menu">
            <a href="{% url "pages:youtubelink-list" %}" class="item"> <i class="align justify icon"></i>View Youtube
                Links</a>
            <a href="{% url "pages:youtubelink-new" %}" class="item"> <i class="add icon"></i>Create Youtube Link</a>
        </div>
    </div>

    <div class="right menu">
        <div class="ui dropdown item">
            Account <i class="dropdown icon"></i>

            <div class="menu">
                <a href="{% url "pages:logout" %}" class="item"> <i class="sign out icon"></i>Logout</a>
            </div>
        </div>
    </div>


</div>

demo_site/pages/templates/semantic-ui/statusbar.html
<div class="ui segment">
    <div class="ui right aligned grid">
        <div class="left floated left aligned ten wide column">

            <div class="ui inverted breadcrumb">
{#                {% load sitetree %}#}
{#                {% sitetree_breadcrumbs from "main_en" template "sitetree/breadcrumbs_semantic.html" %}#}
            </div>

        </div>
        <div class="right floated right aligned one wide column">
            <div id="version_popup" class="small ui icon" data-title="Version info" data-html="{% include "semantic-ui/version.html" %}"><i class="info icon"></i></div>
        </div>
    </div>
</div>

demo_site/pages/templates/semantic-ui/version.html
<b>Version</b>: V0.1 alfa<br>
<b>Created by</b>: Formatics