demo_site/pages/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from demo_site.pages import views

urlpatterns = [
    # Test stuff
    url(r'^grid/(?P<slug>[-\w\d]+)$', views.PageGridList.as_view(), name='grid-list'),
    url(r'^grid/(?P<slug>[-\w\d]+)/new$', views.PageGridCreate.as_view(), name='grid-new'),


    url(r'^grid/edit/(?P<pk>\d+)$', views.PageGridUpdate.as_view(), name='grid-edit'),
    url(r'^grid/delete/(?P<pk>\d+)$', views.PageGridDelete.as_view(), name='grid-delete'),


    url(r'^grid/edit/preview/(?P<pk>\d+)$', views.PageGridUpdate2.as_view(), name='grid-edit2'),
    url(r'^grid/delete/preview/(?P<pk>\d+)$', views.PageGridDelete2.as_view(), name='grid-delete2'),

    # Real stuff
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^page$', views.PageList.as_view(), name='page-list'),
    url(r'^page/new/', views.PageListCreate.as_view(), name='page-new'),
    url(r'^page/edit/(?P<pk>\d+)$', views.PageUpdate.as_view(), name='page-edit'),
    url(r'^page/delete/(?P<pk>\d+)$', views.PageDelete.as_view(),name='page-delete'),
    url(r'^article$', views.PageArticleList.as_view(), name='article-list'),
    url(r'^article/(?P<pk>\d+)$', views.PageArticleDetail.as_view(), name='article-detail'),
    url(r'^article/new$', views.PageArticleCreate.as_view(), name='article-new'),
    url(r'^article/edit/(?P<pk>\d+)$', views.PageArticleUpdate.as_view(), name='article-edit'),
    url(r'^article/delete/(?P<pk>\d+)$', views.PageArticleDelete.as_view(), name='article-delete'),
    url(r'^faq$', views.PageFAQList.as_view(), name='faq-list'),
    url(r'^faq/(?P<pk>\d+)$', views.PageFAQDetail.as_view(), name='faq-detail'),
    url(r'^faq/new$', views.PageFAQCreate.as_view(), name='faq-new'),
    url(r'^faq/edit/(?P<pk>\d+)$', views.PageFAQUpdate.as_view(), name='faq-edit'),
    url(r'^faq/delete/(?P<pk>\d+)$', views.PageFAQDelete.as_view(), name='faq-delete'),
    url(r'^link$', views.PageLinkList.as_view(), name='link-list'),
    url(r'^link/(?P<pk>\d+)$', views.PageLinkDetail.as_view(), name='link-detail'),
    url(r'^link/new$', views.PageLinkCreate.as_view(), name='link-new'),
    url(r'^link/edit/(?P<pk>\d+)$', views.PageLinkUpdate.as_view(), name='link-edit'),
    url(r'^link/delete/(?P<pk>\d+)$', views.PageLinkDelete.as_view(), name='link-delete'),
    url(r'^youtubelink$', views.PageYoutubeLinkList.as_view(), name='youtubelink-list'),
    url(r'^youtubelink/(?P<pk>\d+)$', views.PageYoutubeLinkDetail.as_view(), name='youtubelink-detail'),
    url(r'^youtubelink/new$', views.PageYoutubeLinkCreate.as_view(), name='youtubelink-new'),
    url(r'^youtubelink/edit/(?P<pk>\d+)$', views.PageYoutubeLinkUpdate.as_view(), name='youtubelink-edit'),
    url(r'^youtubelink/delete/(?P<pk>\d+)$', views.PageYoutubeLinkDelete.as_view(),
        name='youtubelink-delete'),
    url(r'^facebooklink$', views.PageFacebookLinkList.as_view(), name='facebooklink-list'),
    url(r'^facebooklink/(?P<pk>\d+)$', views.PageFacebookLinkDetail.as_view(), name='facebooklink-detail'),
    url(r'^facebooklink/new$', views.PageFacebookLinkCreate.as_view(), name='facebooklink-new'),
    url(r'^facebooklink/edit/(?P<pk>\d+)$', views.PageFacebookLinkUpdate.as_view(), name='facebooklink-edit'),
    url(r'^facebooklink/delete/(?P<pk>\d+)$', views.PageFacebookLinkDelete.as_view(),
        name='facebooklink-delete'),
    # url(r'^(?P<slug>[-\w\d]+)$', views.PageView, name='page'),
    #url(r'^', views.IndexView, name='default'),
]

demo_site/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import RedirectView
from .pages import views

urlpatterns = patterns(
    '',
    url(r'', include('django.contrib.auth.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^pages/', include('demo_site.pages.urls', namespace='pages')),

    url(r'^(?P<slug>[-\w\d]+)$', views.PageDetail.as_view(), name='page-detail'),
    url(r'^.*$', RedirectView.as_view(url='pages/page', permanent=False), name='index'),
)

demo_site/pages/models.py
from django.core import urlresolvers
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from smartfields import fields
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from .grid_validator import GridValidator, GridCellValidator


class TimestampAble(models.Model):
    created_on = models.DateTimeField(_("date/time created"), editable=False, auto_now_add=True)
    modified_on = models.DateTimeField(_("date/time modified"), editable=False, auto_now=True)
    created_by = models.ForeignKey(User, editable=False, related_name='%(app_label)s_%(class)s_created_by', null=True,
                                   default=None)
    modified_by = models.ForeignKey(User, editable=False, related_name='%(app_label)s_%(class)s_modified_by', null=True,
                                    default=None)

    class Meta:
        abstract = True


class AbstractPage(models.Model):
    # language = models.CharField()
    slug = models.SlugField(max_length=255, verbose_name='Url', unique=True)

    class Meta:
        abstract = True


class PageFAQ(TimestampAble, AbstractPage):
    question = models.TextField(verbose_name='Question')
    answer = models.TextField(verbose_name='Answer')

    class Meta:
        verbose_name = 'FAQ'
        verbose_name_plural = 'FAQs'

    def __str__(self):
        return 'FAQ: {0}'.format(self.question)


class PageLink(TimestampAble, AbstractPage):
    name = models.TextField(verbose_name='Title') 
    link = models.TextField(verbose_name='Link')

    class Meta:
        verbose_name = 'Link'
        verbose_name_plural = 'Links'

    def __str__(self):
        return 'Internal Link: {0}'.format(self.name)


class PageYoutubeLink(TimestampAble, AbstractPage):
    name = models.TextField(verbose_name='Title') 
    link = models.TextField(verbose_name='Link')

    class Meta:
        verbose_name = 'Youtube link'
        verbose_name_plural = 'Youtube links'

    def __str__(self):
        return 'Youtube Link: {0}'.format(self.name)


class PageFacebookLink(TimestampAble, AbstractPage):
    name = models.TextField(verbose_name='Title') 
    link = models.TextField(verbose_name='Link')

    class Meta:
        verbose_name = 'Facebook link'
        verbose_name_plural = 'Facebook links'

    def __str__(self):
        return str(self.pk)


class Page(TimestampAble, AbstractPage):
    name = models.CharField(max_length=255, verbose_name='Name')
    slogan = models.CharField(max_length=255, verbose_name='Slogan', blank=True, default='')
    summary = models.TextField(blank=True)
    parent = models.ForeignKey('Page', blank=True, null=True, verbose_name='Parent', related_name="Child")
    ordering = models.PositiveSmallIntegerField(verbose_name='Ordering')
    sidebar_right = models.BooleanField(default=True, verbose_name='Sidebar right?')

    class Meta:
        verbose_name = 'Page'
        verbose_name_plural = 'Pages'

    def __str__(self):
        return self.name


class GridCell(TimestampAble):
    CHOICES = (
        (1, 'one'),
        (2, 'two'),
        (3, 'three'),
        (4, 'four'),
        (5, 'five'),
        (6, 'six'),
        (7, 'seven'),
        (8, 'eight'),
        (9, 'nine'),
        (10, 'ten'),
        (11, 'eleven'),
        (12, 'twelve'),
        (13, 'thirteen'),
        (14, 'fourteen'),
        (15, 'fifteen'),
        (16, 'sixteen'),
    )
    # Link Cell to a page
    page = models.ForeignKey(Page, related_name='grid_cells', editable=False)

    # Content object
    content_type = models.ForeignKey(ContentType,
                                     verbose_name=_('content type'),
                                     related_name="content_type_set_for_%(class)s")
    object_pk = models.TextField(_('object ID'))
    content_object = GenericForeignKey(ct_field="content_type", fk_field="object_pk")

    horizontalSize = models.IntegerField(verbose_name='HorizontalSize', choices=CHOICES, default=1)
    horizontalPosition = models.IntegerField(verbose_name='HorizontalPosition', choices=CHOICES, default=1)
    verticalSize = models.IntegerField(verbose_name='VerticalSize', default=1)
    verticalPosition = models.IntegerField(verbose_name='VerticalPosition', default=0)

    def clean(self):
        from django.core.exceptions import ValidationError
        cell = GridCellValidator(self.horizontalPosition,self.verticalPosition,self.horizontalSize,self.verticalSize)
        grid = GridValidator()
        if not grid.add_cell(cell):
            raise ValidationError('Invalid location.')

    class Meta:
        verbose_name = 'Grid'
        verbose_name_plural = 'Grids'

    def get_content_object_url(self):
        """
        Get a URL suitable for redirecting to the content object.
        """
        return urlresolvers.reverse(
            "comments-url-redirect",
            args=(self.content_type_id, self.object_pk)
        )

    def __str__(self):
        return 'Model:{0}, ID:{1}'.format(self.content_type, self.object_pk)


class PageArticle(TimestampAble, AbstractPage):
    name = models.TextField(verbose_name='Title') 
    content = models.TextField(verbose_name='Content')

    class Meta:
        verbose_name = 'Content'
        verbose_name_plural = 'Content'

    def __str__(self):
        return 'Article: {0}'.format(self.name)


class PageFile(TimestampAble, AbstractPage):
    name = models.CharField(max_length=255, verbose_name='Name')
    file = fields.FileField(upload_to='files/%Y/%m/%d', verbose_name='File')

    class Meta:
        verbose_name = 'File'
        verbose_name_plural = 'Files'

    def __str__(self):
        return self.name


class PagePhoto(TimestampAble, AbstractPage):
    name = models.CharField(max_length=255, verbose_name='Name')
    photo = fields.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Photo')

    class Meta:
        verbose_name = 'Photo'
        verbose_name_plural = 'Photo\'s'

    def __str__(self):
        return self.name


class PageForm(TimestampAble, AbstractPage):
    message = fields.TextField(verbose_name='Thank you message')

    class Meta:
        verbose_name = 'Form'
        verbose_name_plural = 'Forms'

    def __str__(self):
        return str(self.pk)


class PageFormElement(TimestampAble):
    form = models.ForeignKey(PageForm, verbose_name='Form', related_name="FormElement")
    name = models.CharField(max_length=255, verbose_name='Element name')
    required = models.BooleanField(verbose_name='Required?')

    class Meta:
        verbose_name = 'Form element'
        verbose_name_plural = 'Form elements'

    def __str__(self):
        return self.name

demo_site/pages/templates/pages/semantic-ui/page-article-delete.html
{% extends "semantic-ui/base.html" %}
{% block title %} Delete item {% endblock %}
{% block statusbar %}
{% endblock %}
{% block sidebar %}
{% endblock %}
{% block content %}
    <div class="ui segment">
        <form method="post">{% csrf_token %}
            <div class="ui negative message">
                <div class="header">
                    Confirm delete
                </div>
                <p>Are you sure you want to delete "{{ object.name }}" ?</p>
            </div>
            <input class="ui red submit button" type="submit" value=" Delete "/>
        </form>
    </div>
{% endblock %}

demo_site/pages/templates/pages/semantic-ui/page-article-list.html
{% extends "semantic-ui/base.html" %}
{% block content %}
        <div>
            <a href="{% url "pages:article-new" %}" class="blue ui labeled icon button"><i class="add icon"></i>New</a>
        </div>
        {% if object_list %}
            <table class="ui blue unstackable striped table">
                <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Content
                    </th>
                    <th>
                        Created on
                    </th>

                    <th>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                </tr>
                </thead>
                <tbody>
                {% for article in object_list %}
                    <tr>
                        <td>
                            <span class="badge">{{ article.name }}</span>
                        </td>
                        <td>
                            {{ article.content }}
                        </td>
                        <td>
                            {{ article.created_on }}
                        </td>
                        <td class="right aligned">
                        </td>
                        <td>
                            <div class="ui buttons">
                                <a href="{% url "pages:article-edit" article.id %}" class="ui positive button">Edit</a>
                              <div class="or"></div>
                                <a href="{% url "pages:article-delete" article.id %}" class="ui negative button">Delete</a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="info">No articles found</div>
        {% endif %}
{% endblock %}

demo_site/pages/templates/pages/semantic-ui/page-detail.html
{% extends "semantic-ui/base.html" %}
{% block content %}

    <div class="ui error message">
      <i class="close icon"></i>
      <div class="header">
        Preview Page
      </div>
      <p>This how the actual page will look like</p>
    </div>

    Page Slug: {{ page.slug }}
    <br />
    Modified By: {{ page.modified_by }}
    <br />
    Modified On: {{ page.modified_on }}
    <br />
    <br />

    <div class="ui stackable grid">
    <div class="stretched row">
        {% for item in grid_items %}
            <div class="{{ item.get_horizontalSize_display }} wide column">

                <div class="ui raised segment">

                    {% if item.content_type.name == 'FAQ' %}
                        {% for content_item in item_instances1 %}
                            {% for content in content_item %}
                                {% if item.object_pk|add:0 == content.id|add:0 %}

                                    <div class="ui accordion">
                                      <div class="title">
                                        <i class="dropdown icon"></i>
                                        {{ content.question }}
                                      </div>
                                      <div class="content">
                                        <p>{{ content.answer|safe }}</p>
                                      </div>
                                    </div>

                                    <div class="tiny ui buttons">
                                        <a href="{% url "pages:grid-edit2" item.id %}" class="ui positive button">Edit</a>
                                    <div class="or"></div>
                                        <a href="{% url "pages:grid-delete2" item.id %}" class="ui negative button">Delete</a>
                                    </div>

                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                    {% endif %}

                    {% if item.content_type.name == 'Youtube link' %}
                        {% for content_item in item_instances %}
                            {% for content in content_item %}
                                {% if item.object_pk|add:0 == content.id|add:0 %}
                                    <div class="ui embed" data-id="{{ content.link }}" data-source="youtube"></div>
                                    <script>
                                        $('.ui.embed').embed();
                                    </script>
                                    <br />
                                    <div class="tiny ui buttons">
                                        <a href="{% url "pages:grid-edit2" item.id %}" class="ui positive button">Edit</a>
                                    <div class="or"></div>
                                        <a href="{% url "pages:grid-delete2" item.id %}" class="ui negative button">Delete</a>
                                    </div>

                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                    {% endif %}

                    {% if item.content_type.name == 'Content' %}
                        {% for content_item in item_instances3 %}
                            {% for content in content_item %}

                                {% if item.object_pk|add:0 == content.id|add:0 %}
                                    <h3>{{ content.name }}</h3>
                                    {{ content.content|safe }}

                                    <div class="tiny ui buttons">
                                        <a href="{% url "pages:grid-edit2" item.id %}" class="ui positive button">Edit</a>
                                    <div class="or"></div>
                                        <a href="{% url "pages:grid-delete2" item.id %}" class="ui negative button">Delete</a>
                                    </div>

                                {% endif %}

                            {% endfor %}
                        {% endfor %}
                    {% endif %}

                    {% if item.content_type.name == 'Link' %}
                        {% for content_item in item_instances2 %}
                            {% for content in content_item %}
                                {% if item.object_pk|add:0 == content.id|add:0 %}

                                    <h3>{{ content.name }}</h3>
                                    {{ content.link|safe }}

                                    <br />
                                    <div class="tiny ui buttons">
                                        <a href="{% url "pages:grid-edit2" item.id %}" class="ui positive button">Edit</a>
                                    <div class="or"></div>
                                        <a href="{% url "pages:grid-delete2" item.id %}" class="ui negative button">Delete</a>
                                    </div>

                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                    {% endif %}
                </div>

            </div>

        {% endfor %}
    </div>
    </div>

    <script>
{#    $('.content.example .ui.embed').embed();#}
{#        $('.ui.embed').embed();#}
        $('.message .close').on('click', function () {
            $(this).closest('.message').fadeOut();
        });
        $('.ui.accordion').accordion();
    </script>

{% endblock %}

demo_site/pages/templates/pages/semantic-ui/page-facebooklink-form.html
{% extends "semantic-ui/base.html" %}
{% load crispy_forms_tags %}
{% block content_header %}
    <section id="page-title">
        <div class="container clearfix">
            <h1>New facebook link</h1>
        </div>
    </section>
{% endblock %}
{% block content %}
    <div class="ui segment">
        <div class="ui divider"></div>
        <div class="row">
            {% if messages %}
                {% for message in messages %}
                    <div class="ui{% if message.tags == 'error' %} negative {% endif %}message">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            <div class="ui form">
            <form method="post">{% csrf_token %}
                {{ form|crispy }}
                <input class="ui blue submit button" type="submit" value=" Submit "/>
            </form>
                </div>
        </div>
    </div>
{% endblock %}

demo_site/pages/templates/pages/semantic-ui/page-facebooklink.html
{% extends "semantic-ui/base.html" %}
{% block content %}
        <div>
            <a href="{% url "pages:facebooklink-new" %}" class="blue ui labeled icon button"><i class="add icon"></i>New</a>
        </div>
        {% if object_list %}
            <table class="ui blue unstackable striped table">
                <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Content
                    </th>
                    <th>
                        Created on
                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                </tr>
                </thead>
                <tbody>
                {% for article in object_list %}
                    <tr>
                        <td>
                            <span class="badge">{{ article.name }}</span>
                        </td>
                        <td>
                            {{ article.link }}
                        </td>
                        <td>
                            {{ article.created_on }}
                        </td>
                        <td class="right aligned">
                        </td>
                        <td>
                            <div class="ui buttons">
                                <a href="{% url "pages:facebooklink-edit" article.id %}" class="ui positive button">Edit</a>
                              <div class="or"></div>
                                <a href="{% url "pages:facebooklink-delete" article.id %}" class="ui negative button">Delete</a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="info">No facebook links found</div>
        {% endif %}
{% endblock %}

demo_site/pages/templates/pages/semantic-ui/page-faq-form.html
{% extends "semantic-ui/base.html" %}
{% load crispy_forms_tags %}
{% block content_header %}
    <section id="page-title">
        <div class="container clearfix">
            <h1>New Faq</h1>
        </div>
    </section>
{% endblock %}
{% block content %}
    <div class="ui segment">
        <div class="ui divider"></div>
        <div class="row">
            {% if messages %}
                {% for message in messages %}
                    <div class="ui{% if message.tags == 'error' %} negative {% endif %}message">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            <div class="ui form">
            <form method="post">{% csrf_token %}
                {{ form|crispy }}
                <input class="ui blue submit button" type="submit" value=" Submit "/>
            </form>
                </div>
        </div>
    </div>
{% endblock %}

demo_site/pages/templates/pages/semantic-ui/page-grid-delete.html
{% extends "semantic-ui/base.html" %}
{% block title %} Delete item {% endblock %}
{% block statusbar %}
{% endblock %}
{% block sidebar %}
{% endblock %}
{% block content %}
    <h1>
        Delete cell for {{ object.page.name }}
    </h1>
    <div class="ui segment">
        <form method="post">{% csrf_token %}
            <div class="ui negative message">
                <div class="header">
                    Confirm delete
                </div>
                <p>Are you sure you want to delete "{{ object.id }}" ?</p>
            </div>
            <input class="ui red submit button" type="submit" value=" Delete "/>
        </form>
{% endblock %}

demo_site/pages/templates/pages/semantic-ui/page-link-form.html
{% extends "semantic-ui/base.html" %}
{% load crispy_forms_tags %}
{% block content_header %}
    <section id="page-title">
        <div class="container clearfix">
            <h1>New link</h1>
        </div>
    </section>
{% endblock %}
{% block content %}
    <div class="ui segment">
        <div class="ui divider"></div>
        <div class="row">
            {% if messages %}
                {% for message in messages %}
                    <div class="ui{% if message.tags == 'error' %} negative {% endif %}message">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            <div class="ui form">
            <form method="post">{% csrf_token %}
                {{ form|crispy }}
                <input class="ui blue submit button" type="submit" value=" Submit "/>
            </form>
                </div>
        </div>
    </div>
{% endblock %}

demo_site/pages/templates/pages/semantic-ui/page-link.html
{% extends "semantic-ui/base.html" %}
{% block content %}

        <div>
            <a href="{% url "pages:link-new" %}" class="blue ui labeled icon button"><i class="add icon"></i>New</a>
        </div>
        {% if object_list %}
            <table class="ui blue unstackable striped table">
                <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Content
                    </th>
                    <th>
                        Created on
                    </th>
                    <th>
                    </th>
                    <th>
                    </th>
                    <th>
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for article in object_list %}
                    <tr>
                        <td>
                            <span class="badge">{{ article.name }}</span>
                        </td>
                        <td>
                            {{ article.link }}
                        </td>
                        <td>
                            {{ article.created_on }}
                        </td>
                        <td class="right aligned">
                        </td>
                        <td>
                            <div class="ui buttons">
                                <a href="{% url "pages:link-edit" article.id %}" class="ui positive button">Edit</a>
                              <div class="or"></div>
                                <a href="{% url "pages:link-delete" article.id %}" class="ui negative button">Delete</a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="info">No page links found</div>
        {% endif %}
{% endblock %}

demo_site/pages/templates/pages/semantic-ui/page-list.html
{% extends "semantic-ui/base.html" %}
{% block content %}
        <div>
            <a href="{% url "pages:page-new" %}" class="blue ui labeled icon button"><i class="add icon"></i>New</a>
        </div>
        {% if object_list %}
            <table class="ui blue unstackable striped table">
                <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Parent
                    </th>
                    <th>
                        Slug
                    </th>
                    <th>
                        Slogan
                    </th>
                    <th>
                        Ordering
                    </th>
                    <th>
                        Created on
                    </th>
                    <th>
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for object in object_list %}
                    <tr>
                        <td>
                            {{ object.name }}
                        </td>
                        <td>
                            {{ object.parent }}
                        </td>
                        <td>
                            <span class="ui label">{{ object.slug }}</span>
                        </td>
                        <td>
                            {{ object.slogan }}
                        </td>
                        <td>
                            {{ object.ordering }}
                        </td>
                        <td>
                            {{ object.created_on }}
                        </td>
                        <td class="right aligned">
                            <div class="ui buttons">
                                <a href="{% url "pages:page-edit" object.id %}" class="ui positive button">Edit</a>
                              <div class="or"></div>
                                <a href="{% url "pages:page-delete" object.id %}" class="ui negative button">Delete</a>
                              <div class="or"></div>
                                <a href="{% url "pages:grid-list" object.slug %}" class="ui purple button">Show grid</a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="info">No pages found</div>
        {% endif %}
{% endblock %}

demo_site/pages/templates/pages/semantic-ui/page-youtubelink.html
{% extends "semantic-ui/base.html" %}
{% block content %}
        <div>
            <a href="{% url "pages:youtubelink-new" %}" class="blue ui labeled icon button"><i class="add icon"></i>New</a>
        </div>
        {% if object_list %}
            <table class="ui blue unstackable striped table">
                <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Content
                    </th>
                    <th>
                        Created on
                    </th>
                    <th>
                    </th>
                    <th>
                    </th>
                    <th>
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for article in object_list %}
                    <tr>
                        <td>
                            <span class="badge">{{ article.name }}</span>
                        </td>
                        <td>
                            {{ article.link }}
                        </td>
                        <td>
                            {{ article.created_on }}
                        </td>
                        <td class="right aligned">
                        </td>
                        <td>
                            <div class="ui buttons">
                                <a href="{% url "pages:youtubelink-edit" article.id %}" class="ui positive button">Edit</a>
                              <div class="or"></div>
                                <a href="{% url "pages:youtubelink-delete" article.id %}" class="ui negative button">Delete</a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="info">No youtube links found</div>
        {% endif %}
{% endblock %}